<?php include('header.php') ?>
<?php include('nav.php') ?>
<div id="history">
	<p>Leads from Henry Dick Coakley in Helotes and Frank Braugton
	 
	<p>SASCA<br/>
	A History ... and then some.</p>
	 
	<p>The main line of this story is taken from an article by Mike Scott.  He and his wife, Lou, have been SASCA members since 1975 and, from the late 70's through most of the 80's, were the editorial team that kept Tale Lites going with a mimeograph machine in their home.  At a party they hosted on the Friday night after an event, members labored over a manual typewriter cutting the stencils.  When a page was finished, other members juiced the mimeograph and, literally, cranked out the issue.  Then we all sat around folding, stapling, addressing, and stamping the issue.  It was like tuning the Fiat in its original state - replace spark plugs, condenser, points, and check the timing at least every 10,000 miles.  There were no computers or extended service periods in those days.  Tale Lites was a joint labor of love and a time for members to get to know each other.  This is not to say that we should return to those days but with SASCA's recent growth, it would be nice to somehow recreate the camaraderie.</p>
	 
	<p>Mike gave me the names of several people who were members in the early days and they provided bits and pieces of SASCA's history.  Among them were George Meeks and Henry Whittle.  I used their reminiscences to fill out the original article.</p>
	 
	<p>In 1948 a group of young men, mainly servicemen who had brought sports cars home from Europe, started racing in the San Antonio area under the name "Happy Bottoms".  (The source of this information refused to expand on the origin of the name.)  It is believed to have been something of a party club as well.  The racing was much like road racing today but much more basic.  Nobody trailed their cars to events.  Tape the headlights on your daily driver, lower the top, remove the windshield, and hit the track.</p>
	 
	<p>The group changed their name to the Vagabonds in 1951.  Late in its life, something called gymkhana became popular and the Vagabonds started running the events.  While much like autocross, gymkhana emphasized low speed, very short, and often imaginative courses.  Over the years, gymkhana in the United States grew and changed.  Courses became longer, faster, and more straightforward.  The name also changed to autocross, probably because it was easier to pronounce and spell.  There was yet another name change, this one by SCCA.  They called gymkhana/autocross to Solo II because they could register the name and then write the rules.  SASCA can not call an event a "Solo II" but autocross is generic.  They still gymkhana in England.  I read an article about it a few years ago.  Their sites are apparently no more than half of the size of our area at Retama Park and often smaller.  The courses are "imaginative" which to them means things like "boxes" in the middle of the course - drive in, stop, back out, and continue the march.</p>
	 
	<p>In 1957, as gymkhana became more popular and road racing more expensive, the Vagabonds splintered.  The main branch changed its name to SASCA.  Our President still uses their gavel to conduct meetings.  SASCA's principle interest remained gymkhana.  The splinter became the Alamo Region of SCCA and its main focus became road racing.  Henry Whittle recalls that, when he came to San Antonio in '59, he was told that he couldn't join the Alamo Region unless he was going to road race.  (Henry has been a SCCA member for 43 years and is still active as Alamo Region's membership chairman.)  Of course, that was nonsense, as he told them.  Alamo Region was forced to accept him as a SCCA member in good standing who was transferring from Kansas City.  While there may have been some animosity between SASCA and Alamo Region, then, as now, some belong to both clubs.  In any event, Alamo Region was so focused on road racing that they even leased Zuel Field, an old airstrip in the area, and set up their own race course.  George Meeks, a SASCA member from about 1960 to 1980 who was also an Alamo Region member, recalls they even had it repaved.  Unfortunately, the paving was done with a surface of pea gravel that, as you can imagine, ruined a number of paint jobs.  They also sponsored a street race in Austin.  Alamo Region had other problems that eventually led to yet another splitter group that, in the '60s, became the Austin chapter of SCCA.  The two smaller groups were unable to maintain their race schedules and there hasn't been road racing in this area for more than 20 years.  But let me get back to SASCA's history.</p></p>
	 
	<p>Two interesting events occurred in 1965.  The first was that SASCA again splintered.  A group with a primary interest in road rallyes became the Checkpointers Sport Rallye Club.  (Do not confuse such events with some of the gimmick rallyes currently run by some of the marquee clubs.)  Over the next ten years, Checkpointers ran numerous events and fathered the "Border Rallye" from San Antonio to Laredo.  Both the Checkpointers and the Border Rallye gained an admirable reputation in south Texas.  Checkpointers also developed an excellent autocross program.  George Meeks recalls that there were several abortive attempts to unify the two organizations.  Seems the major problem was choosing a name for the proposed merger.  The closest the tow negociating teams got was the name ACE (Alamo Car Enthusiasts).  In the mid 70's gasoline prices plus the work involved in putting on a good rallye caused Checkpointers to close its doors.</p>
	 
	<p>The other was a unique issue of Tale Lites.  George Meeks and another member reported first hand coverage from the Sebring road race.  While it seems a trivial task these days, it was a major task to get the photos published for Tale Lites since copies were reproduced using a mimeograph machine.  Pages with photographs were expensive.  Spokes and Alamo Region agreed to share the set up costs so their readers got the report as well.  That was not the only instance of SASCA's cooperation with other clubs.  In the 80's SASCA, the Corpus Christi SCCA Region, and Spokes held TriCrosses.  On a rotating basis, each club hosted an event to see which had the best drivers/machines.  Points were awarded based on the top five drivers from each class and the club with the high number of points won the event.  In the 90's, SASCA hosted a South Texas Championship autocross in November that drew drivers from Houston, Dallas, Corpus, and various towns within that area.  Both the TriCross and the South Texas Championships petered out for a variety of good and bad reasons.</p>
	 
	<p>SASCA also put on their own rallys.  The most interesting series was one In the early 70's, SASCA's Annual Mid Summer All Night Rally.  It start at 9 pm and wandered as far as Buda and Luckenbach.  The short name was “8 Hours of Texas”.  The obvious difficulty in finding checkpoints at night lead to the use of powerful flash lights an the near arrest of one team for spot lighting deer, and illegal method of hunting (Deer will freeze when hit with an intense beam of light making them easy targets.).  These events ended up with a huge, 7 am breakfast.  Why night ralleys?  You beat the heat and make them more interesting.</p>
	 
	<p>As those of you who were members in early 1999 will recall, finding a place to run was difficult after Brooks Air Force Base annulled our contract in favor of renting the space to make the Base more self sufficient.  The same problem has faced SASCA at various times over its long history.  We've run on the east side of Hemisfair before IH 37 was built, at the east end of North Star Mall before the multilevel parking garage was built, on the south side parking area of Central Park Mall, at Kelly Air Force Base, and on a parking lot on the south side of Loop 410 before the building with the bronzed, sloping glass wall was built, and on the lot of Northeast Independent School District's Blossom Athletic Center.  There we occassionally had to change our routine third Sunday date to accommodate the Spurs.  They use to use the Center for practices.  As an interesting sidelight, George Meeks showed me an ad for one of the 1969 events at Central Park Mall.  Entry fees were $2.00 formembers and $3.00 for others.  Registration started at 12:30 and timed runs began an hour later.</p>
	 
	<p>Throughout its history, SASCA has tried to do its part for the community.  In the early years, it held an annual rallye to benefit San Antonio's Boysville.  For at least two years SASCA teams also manned the phones for KLRN's annual auction.  In the mid 80's it held an annual autocross to benefit Easter Seals.  SASCA has held several events to benefit the Air Force Assistance Fund.  From the late '80s until the end of 1998, when base closing pressures made Brooks Air Force Base unavailable, we donated a significant chunk of our entry fees to the Brooks Air Force Base Morale, Welfare, and Recreation Fund.  (If you're wondering about the Air Force connection, it is said that General Curtis Lemay, while heading the Strategic Air Command, bought sports cars from recreation funds and sponsored road races on Air Force Bases to increase his flight crews' competitive edge.)</p>
	 
	<p>One of the more interesting public service events was the "Drunk-cross".  To help publicize the effects of drink on driving, SASCA joined with the then new Mothers Against Drunk Drivers, the San Antonio Police Department, and an anonymous beer distributor.  Selected drivers were timed over a many coned, short course while stone cold sober.  They and several reporters then partook of free beer and were monitored by SAPD breath analyzers to determine their state of inebriation.  At various stages, they again tried the course.  The point being to see how times went up and cones went down.  One member cleaned out more cones than we could count.  Seems he might have done better but, in his drunken state, he just didn't care.  Another, surprisingly, went faster (practice?) and didn't down any cones.  MADD ignored his results.   (It must be admitted that he is one of the finest drivers ever to turn a wheel at our events.  He no longer autocrosses but recently was first in the nation in a street rodder competition taking into account his car's overall appearance, quarter mile time, and handling in an autocross-like event.  This in a car that was driven over 1000 miles to the event and back.)  When it was all over, designated drivers took the drunks home.</p>
</div>
<?php include('footer.php') ?>